# Command execution failure

executor-not-player: "This command can only be executed ingame."
no-message-specified: "You didn't specify a message to send."

# Use {player} for the Player's Name
# Use {message} for the message

chat-design: "§6§lStaffChat §r§7| §e[{player}] » §r{message}"

# With that PREFIX you can send messages to the staff chat, without using the command

staffchat-use-prefix: "*"

# This feature allows messages sent in-game in StaffChat to be displayed in the Discord Server StaffChat channel.

webhook: false
webhook-url: ""
